[[ops]]
name = "reader"
lib_name = "epaxos"

# [[ops]]
# name = "ss"
# lib_name = "epaxos"

[[ops]]
name = "epaxos_server"
lib_name = "epaxos"

[[ops]]
name = "writer"
lib_name = "epaxos"

[[nodes]]
name = "node1"
hostname = "127.0.0.1"
port = 3000

[placement]
  [[placement.reader]]
  nodename = "node1"
  actor_name = "reader"
  server = "epaxos1"
  
  [[placement.epaxos_server]]
  nodename = "node1"
  actor_name = "epaxos1"
  replica_list = ["epaxos1"]
  # replicas = 3
  # replica_list = ["epaxos1", "epaxos2", "epaxos3"]

  # [[placement.ss]]
  # nodename = "node1"
  # actor_name = "epaxos1"

  [[placement.writer]]
  nodename = "node1"
  actor_name = "writer"
  server = "epaxos1"
